version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/montrack
      SPRING_DATASOURCE_USERNAME: montrack_db_owner
      SPRING_DATASOURCE_PASSWORD: npg_52IiqtjsMRLP

  db:
    image: postgres:15
    container_name: montrack-db
    environment:
      POSTGRES_DB: montrack
      POSTGRES_USER: montrack_db_owner
      POSTGRES_PASSWORD: npg_52IiqtjsMRLP
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
