version: '3.8'

services:
  app:
    build: .
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:17.4
    container_name: montrack-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - montrack-data:/var/lib/postgresql/data

volumes:
  montrack-data:
